### ISSUE TITLE
On hover image take full width height of screen

### ISSUE THREAD

**Issue by solankivj94** [imgix/drift#109]
![capture](https://user-images.githubusercontent.com/40413513/47493631-627a0980-d86d-11e8-8248-27a868efa8d4.PNG)

im using flexbox for layout 

            <div class="product-detail__image-main">
                <img src="images/shirt8.jpg" class="demo-trigger" data-zoom="images/shirt9.jpg" alt="6">
            </div>
        
            <div class="product-detail__info main-zoom">
            </div>

             var demoTrigger = document.querySelector('.demo-trigger');
             var paneContainer = document.querySelector('.main-zoom');

             new Drift(demoTrigger, {
             paneContainer: paneContainer,
             inlinePane: false,
             });

**Comment by solankivj94** [comment]
Fixed!!!!  
😓 it had problem with position.
because previously position was absolute. so i changed it to relative and it worked!!!!!

**Comment by frederickfogerty** [comment]
Hey there @solankivj94. Can you please update your issue to follow the issues templates? I'm not too sure what you're discussing here.

**Comment by solankivj94** [comment]
> 
> 
> Hey there @solankivj94. Can you please update your issue to follow the issues templates? I'm not too sure what you're discussing here.

hey @frederickfogerty. i just found that it had issue with  css position of div where zoom was happening.
so it's all working.
thank a lot! :)

**Comment by frederickfogerty** [comment]
Thanks @solankivj94, I'll close this now then :)
