### ISSUE TITLE
Problems using Drift with NPM + Webpack + Babel 5.8

### ISSUE THREAD

**Issue by paulstraw** [imgix/drift#13]
@athal7 is running into an issue using Drift with his JS build setup. Here's an overview of what he's trying to do, to help me set up a minimal replica:

Webpack compiles an index-style JS file with syntax equivalent to the following:

``` javascript
window.MyNamespace = {};
window.MyNamespace.Legacy = {};

import Drift from 'drift-zoom';

window.MyNamespace.Legacy.Drift = Drift;
```

This results in a strange object at `window.MyNamespace.Legacy.Drift`: ![err](https://cloud.githubusercontent.com/assets/117288/12899752/d5faec98-ce67-11e5-8d3b-f7e7b9f70e38.png)

**Comment by paulstraw** [comment]
Hey @athal7, I finally got a chance to dig into this a bit more. I was able to get it working for your setup with the following:

``` javascript
window.MyNs = {};
window.MyNs.Legacy = {};

require('drift-zoom');

window.MyNs.Legacy.Drift = Drift;
```

Can you give that a shot and let me know if it works?

**Comment by athal7** [comment]
@paulstraw thanks for taking a look. Unfortunately no change in behavior here. Happy to pair again if that would be helpful

**Comment by paulstraw** [comment]
Hmm, that's odd. Can you send through your package.json so I can grab all the version numbers etc?

**Comment by athal7** [comment]
Oh did you release a new version to go along with this?

**Comment by paulstraw** [comment]
No, same version. Still 0.1.5.

**Comment by athal7** [comment]
only 0.1.4 is published on npm: https://www.npmjs.com/package/drift-zoom

**Comment by paulstraw** [comment]
Ah, sorry about that! 0.1.5 actually didn't change anything for NPM users, it was just a Bower fix.

**Comment by paulstraw** [comment]
Hey @athal7, 0.1.7 should _finally_ fix this issue entirely, once and for all. Let me know when you have a chance to give it a shot!

**Comment by athal7** [comment]
Thanks @paulstraw! As it turns out, our team has decided to go with a different implementation and I'm working on something else at the moment :(. Hopefully these changes will be helpful for other users though!

If it would be beneficial to you, I can try to double check that it works since you did all of this work.

**Comment by paulstraw** [comment]
That'd be great if you can, but of course no big deal either way. Thanks for the update! I'll go ahead and close this issue.

**Comment by athal7** [comment]
Thanks @paulstraw
