### ISSUE TITLE
Error in destroy function for Drift

### ISSUE THREAD

**Issue by juhaelee** [imgix/drift#14]
I receive the following error when trying to call Drifty's destroy function:
```javascript
Uncaught TypeError: _this._unbindEvents is not a function
```
Shouldn't destroy be:
```javascript
_this.trigger._unbindEvents()
```
? 

I can open a pull request if that is suppose to be the intended function

**Comment by paulstraw** [comment]
Yup, thanks for opening an issue. I'd be quite happy to accept a PR for that fix! :smile:

**Comment by paulstraw** [comment]
Oh. This was taken care of by #16. Closing.
