### ISSUE TITLE
Can't get it to magnify?!

### ISSUE THREAD

**Issue by cjroebuck** [imgix/drift#20]
I can't get it to actually magnify the image it is hovering over

![image](https://cloud.githubusercontent.com/assets/12208/14482864/1bd84c52-0139-11e6-8c7d-9316ec6787c5.png)

my options:

```
const trigger = document.querySelector('.trigger');
new Drift(trigger, {
   inlinePane: true,
   containInline: false,
   sourceAttribute: 'data-zoom'
}); 
```

trigger and sourceAttribute seem to be working ok but just can't get the magification affect. I've also tried setting zoomFactor: 3 and nothing changed.

any ideas what the problem may be? thanks

**Comment by cjroebuck** [comment]
Just fixed it.. problem was zurb foundation setting all img tags to `max-width: auto;` disabling that rule for drift like so `.drift-zoom-pane img { max-width: none; }` was the fix.

**Comment by paulstraw** [comment]
Ah, great. Thanks for the update @cjroebuck!
