### ISSUE TITLE
Animation End not firing on Safari, IE 11

### ISSUE THREAD

**Issue by aghouseh** [imgix/drift#21]
I'm seeing the `drift-opening` and `drift-closing` classes stuck on the exposed `<div class="drift-zoom-pane"/>` after hovering out of the element on Safari 9.1 and IE11. Guessing the issue comes down to a non-prefixed animationend event?

**Comment by paulstraw** [comment]
Interesting, taking a look at this now.

**Comment by aghouseh** [comment]
I was able to manually "complete" the closing by triggering an animationend event in safari directly on the drift-zoom-pane node.

**Comment by paulstraw** [comment]
Hmm. Oddly, I'm not able to replicate this in Safari 9.1 on OS X 10.11.4 (tested using the [demo page](http://imgix.github.io/drift/)). Are there any other steps you're taking to reproduce this?

**Comment by aghouseh** [comment]
Thanks for the quick reply; I'm not able to reproduce it using the demo, so I will try to boil down a test case.

**Comment by paulstraw** [comment]
Very cool, thanks a lot @aghouseh.

**Comment by aghouseh** [comment]
In the meantime, here's a screengrab of it happening to show I'm not insane :) http://i.will.copy.it.to.the.nuggetboard.com/270K3D0N0U2z

**Comment by aghouseh** [comment]
Alright, so it's related to the `animation: noop;` base style. If I edit the stylesheet in the Safari console and remove the custom themed `animation: drift-fadeZoomOut 210ms ease-in;` from the `.drift-zoom-pane.drift-closing`, it never fires the cleanup code. Here's a screengrab of it in action: http://i.will.copy.it.to.the.nuggetboard.com/1W3K141r2z42

**Comment by paulstraw** [comment]
Great catch, figuring out a workaround now.
