### ISSUE TITLE
Why both dist/Drift.js and dist/Drift.min.js are minified?

### ISSUE THREAD

**Issue by SilencerWeb** [imgix/drift#215]
**Question**
Why both dist/Drift.js and dist/Drift.min.js are minified?

**Comment by sherwinski** [comment]
Hi @SilencerWeb, I believe the answer to your question can be found on #76 

> As we now use the Google Closure Compiler we don't have a method to compile the code without also minifying it, but we kept `dist/Drift.js` for backwards-compatibility.

**Comment by SilencerWeb** [comment]
Sad
