### ISSUE TITLE
Feature Request:  Delay before zooming

### ISSUE THREAD

**Issue by WrightSideUp** [imgix/drift#22]
Thanks for putting this out there.  It is working really well for my clients.

Right now the zoomPane is triggered immediately on a mouseenter event.  This can be a little disconcerting if the user is just moving past the trigger element and the mouse happens to touch it.

I would like to have an option to 'debounce' the zoom so that the mouse has to both enter and stay in the trigger element for a configurable time before the zoom pane is actually triggered.

**Comment by paulstraw** [comment]
Great idea @WrightSideUp! I've added `hoverDelay` and `touchDelay` params. Just pass an integer to the option you want to use that specifies the delay in milliseconds (e.g., `hoverDelay: 330`). This has been released as version `0.2.0`.
