### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by SilencerWeb** [imgix/drift#225]
**Question**
I want to see the pane's HTML structure so I could change the styles of it (for example, I need to center the image) but I can't do it because as soon as I lose hover from the image, pane destroys. I'm sure you have a way to prevent this behavior and I would be very thankful if you share it with me :)

**Comment by sherwinski** [comment]
Hi @SilencerWeb, if I understand your question correctly I think you can get around this issue by [pausing script execution](https://stackoverflow.com/a/38783213) via keyboard shortcut. Please note that depending on your browser these steps might vary slightly but for the most part should be the same. Hope that helps!

**Comment by SilencerWeb** [comment]
@sherwinski, or you could consider adding a new option for making pane always visible. Something like, `isPaneVisible`. I left a comment about a similar issue in another repository — https://github.com/jshjohnson/Choices/issues/560#issuecomment-479837379

**Comment by sherwinski** [comment]
@SilencerWeb Since one of the goals of this project is to remain lightweight and expose the simplest API possible, we’re opposed to adding a feature purely for debugging purposes. Closing this ticket since the workaround I provided should suffice.
