### ISSUE TITLE
docs: more noticeable demo

### ISSUE THREAD

**Issue by SilencerWeb** [imgix/drift#226]
**Is your feature request related to a problem? Please describe.**
Right now it is too hard to find a demo in your README. The first thing that I wanted to see is a demo but instead of this I had to scroll all over the README and look for it.

**Describe the solution you'd like**
1. Add a link to the content table

![image](https://user-images.githubusercontent.com/20713191/54861128-06e17880-4d46-11e9-96f2-f24746b53ccc.png)
2. Add a link to the repo's description

![image](https://user-images.githubusercontent.com/20713191/54861132-12cd3a80-4d46-11e9-8f85-496ab632eb7e.png)
3. Add a link as a heading right before "Installation"

![image](https://user-images.githubusercontent.com/20713191/54861138-2aa4be80-4d46-11e9-890c-ea11985ea012.png)

**Additional context**
The screenshots are from repo of the project "Luminous" because this problem concerns it too. You just should understand that the first thing the person who is looking for a zooming library and found your repository in the Google (not on the project's website) wants to see is a demo, not anything else. If you approve this idea I can make pull requests both in this and "Luminous" repo.

**Comment by sherwinski** [comment]
Hey @SilencerWeb thanks for the suggestion. I definitely agree that the demo should be more noticeable for users new to the project and would be happy to accept a PR for this change in both our drift and luminous repos.

**Comment by PeritusDeveloper** [comment]
I would like to work on this issue

**Comment by atlawrie** [comment]
Hi @PeritusDeveloper, thank you so much for letting us know, I'll go ahead and assign you to this issue.

If you haven't already, I would recommend checking out our contributing guide (CONTRIBUTING.md) - there's a few potential gotchas with how we need to title and format our commits to have everything in our pipeline work together nicely.

**Comment by PeritusDeveloper** [comment]
Sure I will go through the contributing guide.
I was planning to add gifs to make the demo noticeable

**Comment by atlawrie** [comment]
Hi @PeritusDeveloper , apologies for the confusion! The issue isn’t that the demo itself isn’t very noticeable, it’s that the link to the demo is hard to find in the context of the readme. The initial comment in the thread outlines a proposed solution, but if you have other suggestions feel free to comment your proposed changes in this thread.

**Comment by sisco0** [comment]
Considering that this is my first contribution to the project, could you kindly check that PR #671 is as expected? **Thank you and have a great day**!

**Comment by atlawrie** [comment]
Hi @sisco0, for the purpose of Octoberfest we're going to work with Peritus on this issue, since they had already expressed their interest and submitted a PR. Thank you very much for your interest though, and hopefully your other PR will serve as a good learning experience in this issue's place.
