### ISSUE TITLE
HoverBounceBox Not Show in the front of image when in Modal

### ISSUE THREAD

**Issue by greatsaiyanman** [imgix/drift#240]
https://codepen.io/greatsaiyanman/pen/YMMmLR

the drift-bouncing-box not show in the front of the image that zoom in modal

@paulstraw

**Comment by paulstraw** [comment]
Just glancing at this, I'm not sure I see what the problem is? This looks like expected behavior as far as I can tell. Can you provide the browser version you're seeing a problem in, along with any other relevant information?

**Comment by greatsaiyanman** [comment]
![error 2](https://user-images.githubusercontent.com/50130665/56946875-08306d00-6b5e-11e9-8622-faaa5050c1d5.PNG)
when i combined drift.js and modal the drift-bouncing-box goes to the back of the modal.

**Comment by paulstraw** [comment]
Ah, I understand what's happening now. The default CSS doesn't specify a z-index for `.drift-bounding-box`. Bootstrap's modal CSS has `z-index: 1050`, so if you set `.drift-bounding-box` to something higher than that, it will display as expected. Adding this to your Pen worked for me:

```
.drift-bounding-box {
  z-index: 1051;
}
```

**Comment by greatsaiyanman** [comment]
Thanks @paulstraw . the drift-bouncing box is display now in the front of image but it exceed in the image. 
![error 3](https://user-images.githubusercontent.com/50130665/56948410-a3c3dc80-6b62-11e9-973d-c891b5ed933e.PNG)
![error 4](https://user-images.githubusercontent.com/50130665/56948418-a9b9bd80-6b62-11e9-8056-2cc436f00bf7.PNG)

check the image

**Comment by paulstraw** [comment]
Just based on the screenshots, it looks like there might be some more CSS elsewhere in your application causing that issue. If you can update your reduced test case to demonstrate this problem, I'm happy to take a look.

**Comment by greatsaiyanman** [comment]
https://codepen.io/greatsaiyanman/pen/YMMmLR

updated codepen

**Comment by paulstraw** [comment]
The only time I'm able to replicate any issues in that example is if I scroll while hovering over the image. When I stop scrolling, the bounding box snaps into place as expected (or closes entirely if my cursor is outside the image bounds at that point). Is this the behavior you're seeing as well, or is what you're seeing unrelated to scrolling?

If you're seeing different behavior, please provide any steps and information that could be helpful in replicating, including your browser version.

**Comment by greatsaiyanman** [comment]
i see the problem in my css. I removed the margin-top in my body at my css. Thanks  @paulstraw
