### ISSUE TITLE
Zooming on click.

### ISSUE THREAD

**Issue by lillehummer** [imgix/drift#25]
Hi there,

I am trying to enable zooming on click, but so far did not succeed. Once I add it to a click event it has to trigger to 'mouseenter' event but when I try to do this using $('.image').trigger('mouseenter'); nothing seems to happen.

I also tried:

```
drifter = new Drift( this, {
        paneContainer: document.querySelector('.product-images')
});

drifter.trigger._show();
drifter.trigger._handleMovement();
```

But this gives weird behavior and the destroy() function does not remove the zoom screen anymore.

Any clues how this could be achieved?

Thanks a bunch for a great plugin by the way, have been using it on a lot of projects already!

**Comment by paulstraw** [comment]
This isn't currently supported behavior. Can you explain what the end goal for the interaction flow is? If I'm understanding correctly, you want it to work like this, correct?

1. User mouses over the thumbnail, nothing happens.
2. User clicks on the thumbnail, triggering a "zoom mode".
3. As the user moves their mouse, Drift works as it would normally.
4. User clicks again (or mouses out) to deactivate the zoom.

**Comment by lillehummer** [comment]
Hi Paul,

Thanks for your reply, that is exactly what I am trying to achieve. Digging deeper into your code I couldn't find anything else I could try. Any clue how it could do this? Thanks a bunch and have a good day!

**Comment by paulstraw** [comment]
Drift doesn't currently support this use case, but I wouldn't be opposed to adding it if it could be done without a large increase in complexity. Would you have any interest in submitting a PR for this, @lillehummer?

**Comment by lillehummer** [comment]
Hi Paul, actually, why not, great idea. :) I am in a busy period right now, but put it on my agenda and will try to work on a PR.
