### ISSUE TITLE
Feature request: Show zoom bounding box on hover

### ISSUE THREAD

**Issue by mseymour** [imgix/drift#26]
There should be a way to have a visual bounding box on the image when hovering.

**Comment by paulstraw** [comment]
@mseymour Totally, that's a feature I've wanted myself since day one! I'm going to try to get this implemented this week. 👍

**Comment by paulstraw** [comment]
Alrighty @mseymour, this is all set in `0.3.0`! I added `hoverBoundingBox` and `touchBoundingBox` options.

**Comment by mseymour** [comment]
There's a bit of an issue regarding it over at issue #28. I'm not sure if it's my setup or if it's an issue with the library itself.
