### ISSUE TITLE
Click to zoom

### ISSUE THREAD

**Issue by alexcarpenter** [imgix/drift#30]
Is there a way to trigger the zoom for desktop on click instead of on hover?

**Comment by paulstraw** [comment]
Hey @alexcarpenter, it sounds like you're looking for the behavior outlined in #25, correct? We don't currently have plans to implement this interaction model. I'm not opposed to a PR that adds it, if it can be done without a large increase in complexity.

Or are you looking for something more like a traditional Lightbox? If so, it might be worth checking out [Luminous](https://github.com/imgix/luminous).

Please feel free to reopen if you have other questions or thoughts.
