### ISSUE TITLE
Browser Support for Safari 8

### ISSUE THREAD

**Issue by zaknafain** [imgix/drift#31]
I have some issues with Safari 8. I found out, that Safari 8 will not support `this.imgEl.style.transform = 'translate(${left}px, ${top}px)';`. I fixed it with the corresponding `this.imgEl.style.webkitTransform = 'translate(${left}px, ${top}px)';`.

Also the zoomed pane is not removed after `onHide`. I haven't found the solution for this though.

Are you interested in support for  Safari 8?

**Comment by paulstraw** [comment]
Hey @zaknafain, thanks for the report. I'll take a look at this!

**Comment by paulstraw** [comment]
This is all set, and released as [0.3.1](https://github.com/imgix/drift/releases). Thanks again!

**Comment by zaknafain** [comment]
Thank you! Updated - Tested - Deployed - Tested again. Working nicely.

**Comment by paulstraw** [comment]
Nice. 👌
