### ISSUE TITLE
Inversed image

### ISSUE THREAD

**Issue by Goufoux** [imgix/drift#323]
Hello,

I have a question, if my image has the property css scaleY (-1), it is not taken into account by drift which displays my image, is there any way to configure this?

If I try to adjust scaleY (-1) to derive-zoom-pane it is not taken into account

Thank you in advance for the answers :)

**Comment by Goufoux** [comment]
I close this issue because i found a solution !

**Comment by sherwinski** [comment]
Hey @Goufoux, glad you were able to find a solution!
I started looking into this issue yesterday and think it's because we are already applying a `transform` property to the `drift-zoom-pane` element -- so it was likely overwriting the `scaleY` property you added.
Mind sharing what your solution was? I am just curious.

**Comment by Goufoux** [comment]
Hello sherwinski,

I transform my images after their upload (in PHP) to provide the image corresponding to the property data-zoom, it is the only solution that I found for the moment (and for lack of time for my project), I would be happy to know if this would be possible afterwards not to have to transform my images and to be able to apply the property on the drift-zoom-pane!

**Comment by sherwinski** [comment]
If you happen to be serving your images through [imgix](https://www.imgix.com/), you can easily [apply the `flip=v`](https://docs.imgix.com/apis/url/rotation/flip) query parameter and imgix will transform the image for you. 
But if you still want to go the CSS route, you will need to find a way to append `scaleY(-1)` to the `transform` property on the zoomed image -- as described in this [SO post](https://stackoverflow.com/a/10765771). This is where I got stuck yesterday and still haven't figured out a workaround for.
Here is a visual example just in case:

Before
<img width="480" alt="Screen Shot 2019-09-09 at 1 11 54 PM" src="https://user-images.githubusercontent.com/15919091/64563449-4572eb80-d304-11e9-8b9e-3a17b52f00e9.png">

After
<img width="480" alt="Screen Shot 2019-09-09 at 1 18 30 PM" src="https://user-images.githubusercontent.com/15919091/64563505-6c312200-d304-11e9-815b-e7382eb2ca76.png">
