### ISSUE TITLE
window.scrollX and window.scrollY compatibility on IE 11

### ISSUE THREAD

**Issue by andreg** [imgix/drift#33]
Hi,

there's an issue of the plugin not being able to properly position the zoom pane on IE 11, because the computation required to assign the `top` and `left` values returns `NaN`.

This can be fixed using `window.pageXOffset` and `window.pageYOffset` instead of `window.scrollX` and `window.scrollY`. As you can see [here](https://developer.mozilla.org/it/docs/Web/API/Window/scrollX), using `window.pageXOffset` is better for cross-browser compat.

**Comment by paulstraw** [comment]
Good catch @andreg, I'll get this fixed up in a second.

**Comment by paulstraw** [comment]
All set, and released as 0.3.2!

**Comment by andreg** [comment]
Thank you!

**Comment by blowsie** [comment]
for better compatibility;
https://github.com/ReactTraining/react-router/issues/605

**Comment by mateusmrosa** [comment]
$(document).ready(function() {
    $(window).scroll(function() {
        var scroll = window.scrollY
        if (scroll > 20) {
            $('.navbar').addClass("sticky")
        } else {
            $('.navbar').removeClass("sticky")

        }
    })
})
