### ISSUE TITLE
[Feature requests] some improve features idea

### ISSUE THREAD

**Issue by tieppt** [imgix/drift#35]
Hi guys, thank you for awesome library!
I have thought and wanna share with you.
- maybe in some scenarios I need border for `ZoomPane` so I can provide css border properties like: `border-width`, `border-style`, `border-color` to `ZoomPane options`.

Thank you all!

**Comment by paulstraw** [comment]
Hey @tieppt, thanks! Glad you're enjoying Drift. You can actually style the ZoomPane however you'd like via CSS. Here's the basic theme, which should give you a good idea of the selectors you'll need to use to get started: https://github.com/imgix/drift/blob/master/src/css/drift-basic.css#L83-L147

If you'd like to use multiple styles for different instances of Drift, you can use the `namespace` option: https://github.com/imgix/drift/blob/master/src/js/Drift.js#L21-L24
