### ISSUE TITLE
The Zoom view not correct with canvas ( object-fit: contain)

### ISSUE THREAD

**Issue by songoten28** [imgix/drift#352]
When im using object-fit: cover in canvas. It working correct.
And then Im change follow this one **fitImageOn**
https://sadique.io/blog/2013/10/03/fitting-an-image-in-to-a-canvas-object/
Now Zoom image View it not correct. 
Im already try to set style for canvas but failed and I don't see any option to set style for ZoomPane
My code
````
const imageURL = URL.createObjectURL(files[0])

const prevImage = new Image();
  prevImage.addEventListener("load", () => {
    // The image can be drawn from any source

      //this is object-fit: contain
      fitImageOn(canvas, prevImage)

      //this is object-fit: cover
    // canvas.getContext("2d").drawImage(
    //     prevImage,
    //     0,
    //     0,
    //     prevImage.width,
    //     prevImage.height,
    //     0,
    //     0,
    //     canvas.width,
    //     canvas.height
    //   );
  });

  prevImage.setAttribute("src", imageURL);
canvas.setAttribute("data-zoom", imageURL);

new Drift(canvas, {
    inlinePane: true,
    touchBoundingBox: true,
    showWhitespaceAtEdges: true,
    hoverDelay: 1500,
    zoomFactor: 5,
    onShow: () => {
      console.log("show");
    },
    onHide: () => {
      console.log("hide");
    }
  });
````

Here is gif file 

![e49f605ec126](https://user-images.githubusercontent.com/11750588/67147968-23399980-f2c4-11e9-900f-9207a702a7dc.gif)

I hope it correct with image (object-fit: contain)

**Comment by luqven** [comment]
I'm going to go ahead and close this issue since it's been quiet for some time. If you're still experiencing this problem please do comment and I'll be glad to open it up again.
