### ISSUE TITLE
Support contributors by displaying them in README.md using all-contributors bot

### ISSUE THREAD

**Issue by frederickfogerty** [imgix/drift#353]
**Before you submit:**

- [x] Please search through the existing issues (both open AND closed) to see if your feature has already been discussed. Github issue search can be used for this: https://github.com/imgix/drift/issues?utf8=%E2%9C%93&q=is%3Aissue
- [x] Please take a moment to find out whether your idea fits with the scope and aims of the project

**Is your feature request related to a problem? Please describe.**
Contributors are extremely important in open-source software. This project has been fortunate enough to have many contributors who have elevated every aspect of the code, documentation, and support far above and beyond what imgix and I could have done ourselves.

**Describe the solution you'd like**
Contributors should be prominently recognised in the README (ideally at the top) by using the [all-contributors bot](https://allcontributors.org/).

**Describe alternatives you've considered**
The all contributors project also has a CLI, but it seems like more work than the bot.

Another alternative is to keep the contributors list we have at the moment, but this isn't very rewarding for contributors.

**Additional context**
N/A

**Comment by sherwinski** [comment]
Hey @frederickfogerty, the all-contributors bot should now be installed. Feel free to use this thread to add anyone for their specific contributions.

Contribution types can be found here: https://allcontributors.org/docs/en/emoji-key

**Comment by frederickfogerty** [comment]
@all-contributors please add @paulstraw for docs, code, and maintenance

**Comment by frederickfogerty** [comment]
@allcontributors please add @sherwinski for code, docs, and maintenance

**Comment by frederickfogerty** [comment]
@allcontributors please add @frederickfogerty for code, docs, and maintenance

**Comment by frederickfogerty** [comment]
@allcontributors please add @jayeb for code, docs, and maintenance
