### ISSUE TITLE
Aspect ratio

### ISSUE THREAD

**Issue by exdeniz** [imgix/drift#36]
I try zoom with aspect ratio, but have - http://i.imgur.com/ZKwIr3w.png
Then I can move the zoom in height only.

How do I do that the image has been full width?

**Comment by exdeniz** [comment]
Fix it: .drift-zoom-pane img { max-width: none; }

**Comment by paulstraw** [comment]
Hey @exdeniz, sounds like this is caused by another selector somewhere in your site's CSS, is that correct?

**Comment by exdeniz** [comment]
Yes, all site have img {max-width: 100%}. May be add to drift css .drift-zoom-pane img { max-width: none; } 
And thanks, drift is amazing plugin.

**Comment by paulstraw** [comment]
Cool, yeah, just wanted to double-check that I understood correctly.

I'll probably just toss in `max-width: none; max-height: none;` to be safe. Will release tomorrow (PDT) as 0.3.4!
