### ISSUE TITLE
Can't make it work with browserify

### ISSUE THREAD

**Issue by heloyo** [imgix/drift#39]
Hi! I am trying to use this package with Browserify, but I can't really make it work.

The command I am running looks like:
`browserify --noparse=drift-zoom example/index.js -o example/build.js -dv`

Doing a `console.log` in browserify shows `noParse: [ 'drift-zoom' ]`. 

The error I get looks like:

```bash
> browserify --noparse=drift-zoom example/index.js -o example/build.js -dv

Error: Cannot find module './util/dom' from 'c:\x\y\z\node_modules\drift-zoom\dist'
    at c:\x\y\z\node_modules\resolve\lib\async.js:55:21
    at load (c:\x\y\z\node_modules\resolve\lib\async.js:69:43)
    at onex (c:\x\y\z\node_modules\resolve\lib\async.js:92:31)
    at c:\x\y\z\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

Any ideas?

**Comment by paulstraw** [comment]
Can you send through the `require` statement you're using in your `example/index.js`?

**Comment by heloyo** [comment]
It is using a `Deku` component I am writing, but the component looks like:

```js
import driftZoom from 'drift-zoom';
```

**Comment by paulstraw** [comment]
Strange. Would it be possible for you to set up a reduced test case I can play with?

**Comment by heloyo** [comment]
Running `npm run build` with those files:

`package.json`:

```json
{
  "scripts": {
    "build": "browserify --noparse=drift-zoom index.js -o test.js -dv"
  },
  "dependencies": {
    "drift-zoom": "^0.3.4"
  },
  "devDependencies": {
    "browserify": "^12.0.1"
  }
}
```


`index.js`:

```js
var driftZoom = require('drift-zoom');
```


Results in this error:

```bash
Error: Cannot find module './util/throwIfMissing' from 'c:\x\y\drift-zoom-test\node_modules\drift-zoom\dist'
    at c:\x\y\drift-zoom-test\node_modules\resolve\lib\async.js:55:21
    at load (c:\x\y\drift-zoom-test\node_modules\resolve\lib\async.js:69:43)
    at onex (c:\x\y\drift-zoom-test\node_modules\resolve\lib\async.js:92:31)
    at c:\x\y\drift-zoom-test\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by paulstraw** [comment]
Perfect, I'll take a look at this tomorrow. Thanks @heloyo!

**Comment by paulstraw** [comment]
Hmmm. @heloyo, I spent a fair bit of time trying to figure out what's going on here. For some reason, Browserify seems to be ignoring(?) `noParse`. I'm unclear why this is happening. In the meantime, you can change your `require` to `require('drift-zoom/dist/Drift.min.js')` to work around this.

**Comment by jmagnusson** [comment]
Weird bug! Changing to `require('drift-zoom/dist/Drift.min.js')` worked, thanks @paulstraw.

**Comment by paulstraw** [comment]
@jmagnusson, I think this was happening because `noParse` needs the full path. Can you try it with the value of `require.resolve('drift-zoom')`?
