### ISSUE TITLE
Drift initialize on multiple items

### ISSUE THREAD

**Issue by gracetouseef** [imgix/drift#437]
Hello guyz, First of all wana say thank you for this great plugin. Am using owl-carousel this works only in first item of the owl-carousel, is there any way i can initialize on the other items.
<div class="owl-carousel owl-theme">
<div class="item">
    <img class="demo-trigger" src="https://demos.imgix.net/wristwatch.jpg?w=200&ch=DPR&dpr=2&border=1,ddd" data-zoom="https://demos.imgix.net/wristwatch.jpg?w=1000&ch=DPR&dpr=2">
</div>
<div class="item">
    <img class="demo-trigger" src="https://demos.imgix.net/wristwatch.jpg?w=200&ch=DPR&dpr=2&border=1,ddd" data-zoom="https://demos.imgix.net/wristwatch.jpg?w=1000&ch=DPR&dpr=2">							
</div>
</div>

initializer =>
var demoTrigger = document.querySelector('.demo-trigger');
	var paneContainer = document.querySelector('.detail');

			new Drift(demoTrigger, {
			  paneContainer: paneContainer,
			  inlinePane: false,
			});

**Comment by ericdeansanchez** [comment]
Hey @gracetouseef thanks for opening up this issue! I'm going to look into this a little bit to hopefully get back to you with a solid answer/guidance on this.

**Comment by ericdeansanchez** [comment]
@gracetouseef while looking into this I found that [OwlCarousel2](https://github.com/OwlCarousel2/OwlCarousel2) has been deprecated as of Jul 31, 2019. _However, I am still looking into this_. Hopefully, we can reach a solution that works with the version of Owl Carousel you are using :)

**Comment by ericdeansanchez** [comment]
Hello @gracetouseef I was hoping to do some more work to help you out on this, but I was hoping to get a few more details about the issues you're having.

Could you explain a bit more about
>Am using owl-carousel this works only in first item of the owl-carousel, is there any way i can initialize on the other items.

Thanks! :)

**Comment by ashug0001** [comment]
Hello @gracetouseef from what I can see you are using `document.querySelector`, this will return a single image, you can use `document.querySelectorAll` to get all the image and call constructor inside a loop, it worked for me.
<pre>
var driftImgs = document.querySelectorAll('.drift-img');
var pane = document.querySelector('.drift-pane');
driftImgs.forEach(img => {
    new Drift(img, {
	paneContainer: pane,
	inlinePane: false
    });
});
</pre>

**Comment by frederickfogerty** [comment]
Hey all, this is something that we believe is best solved in user-land due to the complexity of the issue. I've added @ashug0001's solution to the README which you will be able to look at once #519 is merged!
