### ISSUE TITLE
Problem with position fixed on IE11

### ISSUE THREAD

**Issue by PhilippSchreiber** [imgix/drift#44]
Hey there,

there is a problem with drift, if it is used inside a container wrapper with position:fixed, for example a modal dialog.

Problem appears on IE11.

I have created an isolated test case:

http://codepen.io/PhilippSchreiber/pen/ozrByw

Any idea, how to fix this?

**Comment by paulstraw** [comment]
Hey @PhilippSchreiber, thanks for reporting this, and the 👌  test case. I'm digging now.

**Comment by paulstraw** [comment]
Alrighty @PhilippSchreiber, this is fixed up + released as 0.4.1.

**Comment by PhilippSchreiber** [comment]
Wow @paulstraw that was fast. Thanks a lot!!! 👍 😮
