### ISSUE TITLE
I would like to Drift over more than one image

### ISSUE THREAD

**Issue by Old-Professor** [imgix/drift#470]
I would like to have multiple images on my page and be able to any one of them. I tried several variations like the following. In all cases the second image never appears. I get two instances of the first image and only the first works with drift. What should I do?
`  <body>
    <div>   
    <img class="drift-demo-trigger" data-zoom="IMG%20Files/1-1600.jpg"

        src="IMG%20Files/1-180.jpg"></div> <br> 
    <div><img class="drift-demo-trigger" data-zoom="IMG%20Files/2-1600.jpg"

              src="IMG%20Files/2-180.jpg"></div>
    <div class="wrapper">
      <div class="detail">
        <div>
          <h1 style="font-family: Arial,sans-serif;"><span style="color: red;">Car
              Float Yard<br>
            </span></h1>
          <h1 style="font-family: Arial,sans-serif;"></h1>
          <div style="text-align: left; width: auto; height: auto; font-family: Arial,sans-serif; 
                      font-size: medium; margin-left: 4px;">Blah <br>
            <br>
           Blah<br>
            <br>
            Blah</div>
          <p class="responsive-hint"><span style="color: #cc66cc;">(Psst…&nbsp;Move
              your mouse over the image (or touch it). Also try making your
              browser window smaller!)</span></p>
        </div>
      </div>
    </div>
 `

**Comment by ericdeansanchez** [comment]
Hey 👋 thanks for opening this issue! I am going to be looking into this for you. The example above is very much appreciated and I'll ping you if I find I need anymore details.

**Comment by frederickfogerty** [comment]
Hey all, this is something that we believe is best solved in user-land due to the complexity of the issue. I've added some example solutions to the README which you will be able to look at once #519 is merged!
