### ISSUE TITLE
Webpack: Module parse failed

### ISSUE THREAD

**Issue by Pszek** [imgix/drift#49]
Hi,

I get below error when I import/require Draft. Is it possible to run it with Webpack?

![zrzut ekranu 2016-12-22 o 16 26 48](https://cloud.githubusercontent.com/assets/10253750/21431384/4b316f6a-c867-11e6-885c-14d66c559ba3.png)

**Comment by theog** [comment]
The issue here is package.json main prop should point to the distribution folder where it has been transpiled as apposed to the src. I have forked this project for now, hoping a fix can be allied soon.

**Comment by Pszek** [comment]
@theog thank you for kind help.
