### ISSUE TITLE
NPM package README needs to be updated

### ISSUE THREAD

**Issue by mprydz** [imgix/drift#527]
Found the package on npm but noticed it's missing some info on the npm readme vs the github readme.

**Comment by ericdeansanchez** [comment]
Hey 👋 thanks for opening this issue! At this moment I can see a couple discrepancies.

Was there anything in particular you would like to see in the NPM readme that is in the GitHub readme (or vice versa)?

**Comment by sherwinski** [comment]
Looks like #519 is the big one in addition to some general restructuring from last year. We'll publish a new release and get these sync'd up 👍
