### ISSUE TITLE
Add documentation about positioning the zoom box

### ISSUE THREAD

**Issue by SalehBagheri** [imgix/drift#59]
how to use drift in right to left boxes?

or 

how to change zoom box position at right?

**Comment by Michael-Herzog** [comment]
Hi,

perhaps this helps someone:

`	.drift-zoom-pane img {
		left: 0;
	}`

**Comment by frederickfogerty** [comment]
Hey @SalehGladius and @Michael-Herzog 👋 

Fred from Imgix here - I'll be responsible for the maintenance of this repo from today onwards.

I believe we can solve this issue by updating the documentation to include an example of how to position the zoom box. Would you agree that this would solve your issue?

**Comment by frederickfogerty** [comment]
Hey @Michael-Herzog thanks for the comment. We are looking to support RTL environments. How would you expect drift to work in a RTL environment? Thanks in advance.

**Comment by Michael-Herzog** [comment]
Like this:
http://demo.smartstore.com/frontend/ja/ladies-flag-t

**Comment by bobbygerez** [comment]
@Michael-Herzog @SalehGladius did you find way how to change the zoom box position. Thanks.

**Comment by Michael-Herzog** [comment]
You can fix the problem this issue was originally created for by adding the css I've posted on Mar 21.

**Comment by sherwinski** [comment]
Closing as there hasn't been much activity on here lately and it looks like an answer has been provided.
