### ISSUE TITLE
The demo on the index.html page from the drift-main folder works very crookedly.

### ISSUE THREAD

**Issue by abvas** [imgix/drift#603]
Version 1.4.2
The demo on the index.html page from the drift-main folder works very crookedly. Doesn't work in my application either.
I tried the same error in Firefox 85 and Google Chrome 88 browsers.
Although version v1.4.1 worked correctly.
What do you recommend. Maybe I upupsit something and did something wrong?
Thank!

**Comment by frederickfogerty** [comment]
Hi there @abvas, thank you for opening this issue 👋  I will see if we can internally schedule some time this week to take a look at this. We'll get back to you on here

**Comment by luqven** [comment]
Hey @abvas, the latest [release](https://github.com/imgix/drift/releases/tag/v1.4.3) should address the index.html example page issues. Thanks again for bringing this to our attention.
Please feel free to open this issue again if there’s anything we missed.
