### ISSUE TITLE
Add passive option to event listeners

### ISSUE THREAD

**Issue by BrayanCaro** [imgix/drift#640]
**Before you submit:**

- [X] Please search through the existing issues (both open AND closed) to see if your feature has already been discussed. Github issue search can be used for this: https://github.com/imgix/drift/issues?utf8=%E2%9C%93&q=is%3Aissue
- [X] Please take a moment to find out whether your idea fits with the scope and aims of the project

**Is your feature request related to a problem? Please describe.**
Some times events like `touchstart` or `touchmove` can be very expensive and modern browsers support `passive` listeners, and we can bring the opportunity to use them. 

If we use [Lighthouse](https://developers.google.com/web/tools/lighthouse/), the app warns:
> ##### Does not use passive listeners to improve scrolling perfomance
> Consider marking your touch and wheel event listeners as `passive` to improve your page's scroll performance. [Learn more](https://web.dev/uses-passive-event-listeners/?utm_source=lighthouse&utm_medium=devtools).
> 
> Source
> 
> - Trigger.js:108
> - Trigger.js:110
> 

Those lines, respectively, are as follows:

https://github.com/imgix/drift/blob/77b2bee780a9e0a11bf3642fbd424badfde96d2d/src/js/Trigger.js#L84
https://github.com/imgix/drift/blob/77b2bee780a9e0a11bf3642fbd424badfde96d2d/src/js/Trigger.js#L86

**Describe the solution you'd like**
I would like to pass an option through the constructor, something like:

```js
new Drift(img, {
  passive: true, // default: false
});
```

This ensures that it is only used by users who want it.

**Describe alternatives you've considered**
We can add the param `passive` in [`Trigger.js`](https://github.com/imgix/drift/blob/77b2bee780a9e0a11bf3642fbd424badfde96d2d/src/js/Trigger.js) and write

```js
this.settings.el.addEventListener("touchstart", this._handleEntry, {passive: this.passive});
```

**Additional context**
[NA]

**Comment by frederickfogerty** [comment]
Hey, thanks for the issue @BrayanCaro. I've added to this to our backlog, and hopefully we can tackle it at some point. On the other hand, if you'd like to submit a PR for this, we'd be glad to accept it!

**Comment by frederickfogerty** [comment]
Sounds good @BrayanCaro, let me know if you need any support from our side!
