### ISSUE TITLE
Is there a way to show the zoomed area around the mouse?

### ISSUE THREAD

**Issue by a-tonchev** [imgix/drift#656]
Is there a way to see in a rectangle the zoomed area around the mouse, e.g. something like this:

![image](https://user-images.githubusercontent.com/54528540/157722858-628ac3b9-218c-4b10-a60e-5d45623e8ada.png)

**Comment by frederickfogerty** [comment]
Hey @a-tonchev, thanks for opening the issue. At this stage no, but we'd be happy to have a PR to implement this functionality if you feel like it. For now I'm going to close this issue as we won't likely find a place on our roadmap to implement this.
