### ISSUE TITLE
TypeError: driftImgs.map is not a function

### ISSUE THREAD

**Issue by dngraphisme** [imgix/drift#680]
Hello team @paulstraw ,

Thank you for the library however i have a problem that i can't solve.

I need to work on a viewer in my webpack stack for product sheet under Prestashop 1.7

If I use this code to do a foreach on several images 

```
const driftImgs = document.querySelectorAll('.drift-img');
            console.log(driftImgs)
            const pane = document.querySelector('.drift-pane');
            driftImgs.map(img => {
                new Drift(img, {
                    paneContainer: pane,
                    inlinePane: false
                });
            });
```

I get this error: TypeError: **driftImgs.map is not a function**

----

I work with Jquery, so I tried an each function on the class: .drift-img

But there also impossible to instantiate the library.

Do you have an idea ?

Thank you in advance, regards Nicolas

**Comment by dngraphisme** [comment]
Ok I got it with this code :

```
driftImgs.forEach(function (img) {
                 new Drift(img, {
                     paneContainer: pane,
                     inlinePane: false
                 });
             });
```

Thanks again :)

**Comment by atlawrie** [comment]
Hello! I'm gonna go ahead and close this ticket since it looks like you've gotten it working; feel free to reopen if this is still posing problems.
