### ISSUE TITLE
Nuxt.js imgix/drift

### ISSUE THREAD

**Issue by bobbygerez** [imgix/drift#72]
**Before you submit:**

- [ ✔] Please search through the existing issues (both open AND closed) to see if your issue has been discussed before. Github issue search can be used for this: https://github.com/imgix/drift/issues?utf8=%E2%9C%93&q=is%3Aissue
- [✔ ] Please ensure the problem has been isolated and reduced. This link explains more: http://css-tricks.com/6263-reduced-test-cases/

**Describe the bug**
Using `import Drift from 'drift-zoom';` works fine in nuxt.js.
Here is the complete code and a screenshot.
```
<script type="text/javascript">
import Drift from 'drift-zoom';
 export default{
 mounted(){
    	var demoTrigger = document.querySelectorAll('.demo-trigger');
  		var paneContainer = document.querySelector('.detail');

      	for (var i = 0, len = demoTrigger.length; i < len; i++) {

  		      	new Drift(demoTrigger[i], {
      				  paneContainer: paneContainer,
      				  inlinePane: false
      				});
  			}
  }
</script>
```
![1](https://user-images.githubusercontent.com/10149942/43130132-a33f831e-8f3e-11e8-81ce-e1f9b4173676.png)

But when I used the 
```
if (process.browser) {
  Drift = require.resolve('drift-zoom');
}
```
This is the result..
 ![untitled](https://user-images.githubusercontent.com/10149942/43079600-33d53ada-8e96-11e8-87fa-8cc9ef361f71.png)

The problem in nuxt.js is when you reload it will give first window or document undefined?. Reference for adding nuxt.js https://nuxtjs.org/faq/window-document-undefined/

Here is the screenshot when reload.

![2](https://user-images.githubusercontent.com/10149942/43131093-dccc0bb4-8f40-11e8-8f6b-6addb989d1f8.png)

Below is the code to implement.
```
let Drift;
if (process.browser) {
  Drift = require.resolve('drift-zoom');
}

```
I search it here https://github.com/imgix/drift/issues/39 but it seems it doesn't work. 

```
let Drift;
if (process.browser) {
  Drift = require('drift-zoom/dist/Drift.min.js')
}
```

I can't demonstrate it in the codepen because it's a Server Side Rendering.

Steps to reproduce the behaviour:

**Expected behaviour**
Using `import Drift from 'drift-zoom';` works fine but when reload it will give you document is undefined...
Using ` Drift = require.resolve('drift-zoom')`; doesn't work as it gives you error `Drift is not a constructor`

**Information:**

- drift version: [e.g. v1.3.0]
-Nuxt.js 1.4.0

**Comment by frederickfogerty** [comment]
Hey @bobbygerez thanks for the bug report. Can you please provide a complete sample project displaying this error? I have no experience with Nuxt.js and thus it is not trivial for me to debug this error.

Also, please reformat the issue into the bug report template.

**Comment by mrborek** [comment]
@bobbygerez , did you try with: How to use external resources? https://nuxtjs.org/faq

**Comment by bobbygerez** [comment]
I tried it and it's not working... Here is the code and screenshots.
 ```
head () {
    return {
      script: [
        { src: 'https://s3-us-west-2.amazonaws.com/s.cdpn.io/164071/Drift.min.js' }
      ],
    } 
  },
```
![error1](https://user-images.githubusercontent.com/10149942/43138627-26c7778c-8f58-11e8-8bf9-bb32a86bfe5b.PNG)

![error2](https://user-images.githubusercontent.com/10149942/43138651-382bca28-8f58-11e8-9ce1-ce433060b92d.PNG)

**Comment by mrborek** [comment]
Your file is not working for me also.
Try http://yourjavascript.com/91402132287/drift-min.js
It's 1.3 version.

**Comment by bobbygerez** [comment]
It works like a charm... Thanks.. @mrborek

**Comment by frederickfogerty** [comment]
Hey @bobbygerez thanks for reformatting into the issue template. Is this solved? Do we need to do anything here?

**Comment by bobbygerez** [comment]
@frederickfogerty yeah it was solved.
```
module.exports = {
       script: [
      {
        src: "http://yourjavascript.com/24511711480/drift-min.js"
      },
    ]
  }
```
Add it as global external source and it works like a charm...

**Comment by frederickfogerty** [comment]
Great, I'll close this then.
