### ISSUE TITLE
drift.hide() does not hide zoomPane

### ISSUE THREAD

**Issue by nikugogoi** [imgix/drift#73]
currently I have only seen the option for disabling the trigger to show the zoom pane. The resulting behaviour is that even after the trigger is disabled the zoom pane does not disappear if active. So, one might need to programmatically hide/remove the zoom pane.
After going through your code I was able to do the same like this :
```
var drift = new Drift(document.querySelector("img"), {
  inlinePane : true,
  paneContainer: document.querySelector("p")
});
// disabling trigger and hiding/removing the zoom pane
drift.disable();
drift.zoomPane.hide();
```
Please let me know if there is a better way or we could expose the `hide` method in the `drift` instance in a proper way

**Comment by thomas-obernberger** [comment]
smth to destroy the plugin would also be very nice!

**Comment by frederickfogerty** [comment]
Hi @nikugogoi thanks for the issue. I think it makes sense for `drift.disable()` to also ensure that the ZoomPane is hidden, so we should update this behaviour. Is this in line with what you'd expect to happen?

**Comment by nikugogoi** [comment]
hi @frederickfogerty, I have no problem in the behaviour that you mention. I just thought there should be a way in which we can remove/hide the zoompane in the DOM. So I am leaving the implementation to you guys, who are managing this awesome package :+1: , to ensure we are on the same page.

**Comment by frederickfogerty** [comment]
Awesome, thanks @nikugogoi we'll get onto this when we focus on this package next (not sure when that will happen, could be a month or so).
