### ISSUE TITLE
Enable Use in Server-Side-Rendered Project

### ISSUE THREAD

**Issue by WrightSideUp** [imgix/drift#74]
- [X] Please search through the existing issues (both open AND closed) to see if your feature has already been discussed. Github issue search can be used for this: https://github.com/imgix/drift/issues?utf8=%E2%9C%93&q=is%3Aissue
- [X] Please take a moment to find out whether your idea fits with the scope and aims of the project

**Is your feature request related to a problem? Please describe.**
Enable library to be used in a server-side-rendering Project.  `var d = new Drift()` cannot be called on the server since it heavily relies on the DOM, but right now the library has some checks that cause errors in a server environment if the library is `import`ed that could be changed.

**Describe the solution you'd like**
ZoomPane.js contains a check at the beginning:
```
var divStyle = document.createElement("div").style;

const HAS_ANIMATION =
  typeof document === "undefined" ? false : "animation" in divStyle || "webkitAnimation" in divStyle;
```

This causes an error on the server on `import` even if no Drift is created.  I believe these lines could be changed to 
```
let HAS_ANIMATION = true
if (typeof document !== 'undefined') {
  const divStyle = document.createElement('div').style
  HAS_ANIMATION = 'animation' in divStyle || 'webkitAnimation' in divStyle
}
```
to enable the file to be imported on the server without error.

**Describe alternatives you've considered**
This could be implemented in other ways, like moving the check into the ZoomPane class itself.

**Additional context**
I'd be happy to submit a pull request.

**Comment by WrightSideUp** [comment]
I am using React/Redux, but I don't think those dependencies make any difference (although Drift would make a nice React component if that's a direction you're interested in 👍.

I forked the repo, and made the change outlined in the initial request and it works like a champ.  That is the only DOM-dependent code that gets called outside the Drift classes themselves -- in fact I believe that is the only code in the library _period_ that executes outside the classes.

Once there is nothing that gets executed on `import` then there is no problem on the server.

I'll submit a pull shortly....

**Comment by frederickfogerty** [comment]
Hey @WrightSideUp how is the PR looking? 

We've discussed React support internally and we'd look at "supporting" by publishing some examples of how a user could adapt this library to work in React, rather than publishing an official React component. It seems that you use this library inside of React - is there any chance you would be able to publish a sample repo/example, say under `examples/react/`? 🙌

**Comment by WrightSideUp** [comment]
Sorry I haven't had a chance to get to it yet, but will try to get it done
by the end of the week.

I could put together a React example but it would have to be built from
scratch -- the actual code from my application has way too much other stuff
in it.

It would be possible to put together a nice little demo though....

**Comment by frederickfogerty** [comment]
All good @WrightSideUp 😊 take your time

**Comment by jgillich** [comment]
Just ran into this as well. Any news? :wink:

**Comment by sarathak** [comment]
i'm doing this way 

if(typeof(document) == 'undefined')
        return;
  const Drift = require('drift-zoom').default;

**Comment by songoten28** [comment]
Full code:

`let Drift;
if (typeof window !== 'undefined') {
    Drift = require('drift-zoom').default
}`

**Comment by miljan-aleksic** [comment]
I have open a PR (https://github.com/imgix/drift/pull/407) in attempt to fix this issue, but I might need some help in the testing part as requested by the maintainers.

**Comment by sherwinski** [comment]
Closing as there hasn't been much activity on here lately and it looks like several answers have been provided.
