### ISSUE TITLE
API-Calls like setZoomImageURL(), destroy() can not be found in the minified version of drift.js

### ISSUE THREAD

**Issue by hubert-ried** [imgix/drift#81]
Hi everybody,

it seems, that the api-functions provided by drift.js  are not packed in the current drift.min.js (1.3.1)

```
            var trigger = document.querySelector('.my-selector');
            var drift = new Drift(trigger, {
                paneContainer: document.getElementById('zoom-area')
            });
            drift.destroy();

exception: drift.destroy is not a function

```
I installed through bower and also directly download the repository. The methods enable(), disable(), destroy(), setZoomImageURL() do not reside in the minified version 1.3.1.

What am I missing?

Thanks a lot and all the best from here.
Hube

**Comment by frederickfogerty** [comment]
Hi there @hubert-ried. This is certainly not intended! I'll have a look at this issue sometime this week.
