### ISSUE TITLE
Reinit drift with new options

### ISSUE THREAD

**Issue by hubert-ried** [imgix/drift#82]
Hi everybody,

I need to use drift.js along with a image slider (it is a slick slider).
The current selected slide is shown in an seperate element that is used by drift.

In the slider there can be images with different resolutions. For getting the max zoom factor, I want to calculate the drift zoomFactor dynamically each time the slide changes and want drift to use that current zoomFactor.

I could not find a way to do so other than start a new drift instance every time as slide has changed.
This does not look like a good idea to me.
I am also having trouble with the hoverBoundingBox (each time an instance is created, a new bounding box is created) and updating the pane container (sometimes the pane container updates only, when I mouseout and mousover the trigger element ) ... 

So: 
Wouldn't it be great to have a method where a single drift instance can be called to reinitialize with a different set of options or a method where I can explicitly set an desired option?

I'll love it ... :-) 

Thanks anyway and all the best from here!

**Comment by frederickfogerty** [comment]
Hey there @hubert-ried 👋 

This should be able to be accomplished right now with `.destroy()`. If you call `.destroy` and then reinitialise the component with your new options.

Thanks, Fred
