### ISSUE TITLE
Wrong zoomer position on hover

### ISSUE THREAD

**Issue by DreaMinder** [imgix/drift#86]
**Problem**
At first moment when zoomer appears, zoomed image inside has wrong position or invisible. When cursor moves along, zoomer works fine.

**Reproduce**
1. Go to https://juliapomoshko.com/en/store/coat-grey-long-with-belt
2. Hover your cursor over image with a fast move and stop.

**Additional context**
I use drift-zoom inside of vue.js component. Version with the issue is 1.3. And 1.2 works fine (but has iOS bug, so I can't use it instead).

**Comment by DreaMinder** [comment]
@frederickfogerty hi. It doesn't build on windows =(
But I'm sure you got this, looking forward for release 
Thanks for awesome package, btw!

**Comment by frederickfogerty** [comment]
@DreaMinder would it help if I sent you a compiled version of the `dist` folder?

**Comment by DreaMinder** [comment]
@frederickfogerty I guess so, drop it here dreaminder7@gmail.com, I'll test it

**Comment by DreaMinder** [comment]
@frederickfogerty oh nevermind, I already installed new release, works like a clockwork!
