### ISSUE TITLE
Grow animation

### ISSUE THREAD

**Issue by jackmcdade** [imgix/drift#9]
Is there any way to have the Drift image "grow" from the original, like the way http://fat.github.io/zoom.js/ does?

**Comment by paulstraw** [comment]
Hmmmm. That specific example looks like more of a [Luminous](https://github.com/imgix/luminous) thing. With Drift, you could do something similar-ish with `inline: true` and messing with the CSS animation, but it would be limited to the size of the containing element. If you don't mind it always coming from the center of the screen, you could use `inline: false` and tweak the CSS animation. Either of those sound like they might get you close to what you're thinking?

**Comment by jackmcdade** [comment]
Rats, i posted on the wrong repo. My bad!

**Comment by paulstraw** [comment]
Hah! No problem.
